name: Angular Build Test Deploy

on:
  push:
    paths:
      - "angular-app/**"
      - ".github/workflows/angular-deploy-gh-pages.yml"
  workflow_dispatch: # manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./angular-app
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm install
      - run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./angular-app
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm install
      - run: npm run test-ci

  deploy:
    needs: test

    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url}}

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./angular-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: configure gh pages
        uses: actions/configure-pages@v4

      - name: Build Angular app to prod
        run: npm install && npm run build:prod

      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: angular-app/dist/browser

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
