name: Build dotnet app

on:
  push:
    paths:
      - "dotnet-app/**"
      - ".github/workflows/dotnet-app.yml"
  workflow_dispatch: # manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./dotnet-api
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: use dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "9.x"

      - run: dotnet build dotnet-api.csproj
