name: gh cli, env example

on:
  push:
    paths:
      - ".github/workflows/gh.yml"
  workflow_dispatch:

jobs:
  cli:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: env # https://cli.github.com/manual/gh_help_environment
      - run: gh --version
      - run: gh auth status
      - run: gh repo list
      - run: gh issue list
      - run: gh workflow list
      - run: gh api /repos/:owner/:repo/actions/workflows
